spring:
  application:
    name: gateway-service

server:
  port: 8080

ribbon:
  eureka:
    enabled: false

zuul:
  routes:
    first-service:
      url: http://localhost:8081
      path: /1/**
    second-service:
      url: http://localhost:8082
      path: /2/**